PS C:\Juan Cruz\uader\sw2\tp1\src\chatGPT> pylint python_gpt.py
************* Module python_gpt
python_gpt.py:58:11: W0718: Catching too general exception Exception (broad-exception-caught)

------------------------------------------------------------------
Your code has been rated at 9.70/10 (previous run: 8.48/10, +1.21)
